apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: psd-converter

resources:
- ../../base


images:
- name: PLACEHOLDER_IMAGE
  newName: <your-registry>/psd-converter
  newTag: <your-tag>

patches:
- target:
    kind: Ingress
    name: psd-converter-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: <your-domain>
