apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: psd-converter

resources:
- ../../base


images:
- name: PLACEHOLDER_IMAGE
  newName: registry.k3s.stas-yr.ru/psd-converter
  newTag: v0.0.1

patches:
- target:
    kind: Ingress
    name: psd-converter-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: psd.k3s.stas-yr.ru
