apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: psd-converter-ingress
  namespace: psd-converter
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "500m"
spec:
  ingressClassName: nginx
  rules:
  - host: PLACEHOLDER_HOST
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: psd-converter-service
            port:
              number: 80
